export enum TEAM_TYPE {
  CLUB = "CLUB",
  NATIONAL = "NATIONAL",
}

export enum LEVEL {
  FIVE_STARS = "FIVE_STARS",
  FOURS_AND_A_HALF_STARS = "FOURS_AND_A_HALF_STARS",
  FOUR_STARS = "FOUR_STARS",
}

export const LEVELS = [
  { label: "5 sao", value: LEVEL.FIVE_STARS },
  { label: "4 sao rưởi", value: LEVEL.FOURS_AND_A_HALF_STARS },
  { label: "4 sao", value: LEVEL.FOUR_STARS },
];

export const FIVE_STARS_CLUBS = [
  "Real Madrid",
  "FC Barcelona",
  "Manchester City",
  "Bayern Munich",
  "Arsenal",
  "Liverpool",
  "Bayer Leverkusen",
  "Inter",
  "Paris Saint-Germain",
];

export const FIVE_STARS_NATIONALS = [
  "Argentina",
  "Brazil",
  "France",
  "Portugal",
  "Netherlands",
  "Spain",
  "England",
  "Portugal",
];

export const FOURS_AND_A_HALF_STARS_CLUBS = [
  "Atlético Madrid",
  "Chelsea",
  "Manchester United",
  "Tottenham Hotspur",
  "Newcastle United",
  "Aston Villa",
  "Borussia Dortmund",
  "Napoli",
  "AC Milan",
  "Roma",
  "Sevilla",
  "RB Leipzig",
  "Marseille",
  "Galatasaray",
];

export const FOURS_AND_A_HALF_NATIONAL_TEAMS = [
  "Uruguay",
  "Croatia",
  "Denmark",
  "Switzerland",
  "Serbia",
  "Sweden",
  "Norway",
  "Poland",
  "Mexico",
  "United States",
  "Colombia",
  "Chile",
  "Czech Republic",
  "Turkey",
  "Austria",
  "United States",
];

export const TEAMS = {
  [TEAM_TYPE.CLUB]: {
    [LEVEL.FIVE_STARS]: [
      "Real Madrid",
      "FC Barcelona",
      "Manchester City",
      "Bayern Munich",
      "Arsenal",
      "Liverpool",
      "Bayer Leverkusen",
      "Inter",
      "Paris Saint-Germain",
    ],
    [LEVEL.FOURS_AND_A_HALF_STARS]: [
      "Atlético Madrid",
      "Chelsea",
      "Manchester United",
      "Tottenham Hotspur",
      "Newcastle United",
      "Aston Villa",
      "Borussia Dortmund",
      "Napoli",
      "AC Milan",
      "Roma",
      "Sevilla",
      "RB Leipzig",
      "Marseille",
      "Galatasaray",
    ],
    [LEVEL.FOUR_STARS]: [
      "Real Sociedad",
      "Real Betis",
      "Villarreal",
      "Athletic Club",
      "Lazio",
      "Atalanta",
      "Fiorentina",
      "West Ham United",
      "Brighton & Hove Albion",
      "Bournemouth",
      "Wolverhampton Wanderers",
      "Monaco",
      "Lille",
      "PSV Eindhoven",
      "Ajax",
    ],
  },
  [TEAM_TYPE.NATIONAL]: {
    [LEVEL.FIVE_STARS]: [
      "Argentina",
      "Brazil",
      "France",
      "Portugal",
      "Netherlands",
      "Spain",
      "England",
      "Portugal",
    ],
    [LEVEL.FOURS_AND_A_HALF_STARS]: [
      "Uruguay",
      "Croatia",
      "Denmark",
      "Switzerland",
      "Serbia",
      "Sweden",
      "Norway",
      "Poland",
      "Mexico",
      "United States",
      "Colombia",
      "Chile",
      "Czech Republic",
      "Turkey",
      "Austria",
      "United States",
    ],
    [LEVEL.FOUR_STARS]: [
      "Japan",
      "South Korea",
      "Australia",
      "Nigeria",
      "Cameroon",
      "Morocco",
      "Egypt",
      "Algeria",
      "Costa Rica",
      "Ecuador",
      "Peru",
      "Paraguay",
      "Scotland",
      "Republic of Ireland",
      "Wales",
    ],
  },
};
